src/HotelCollab/Controllers/HotelController.cs
namespace HotelCollab.Controllers
{
    using HotelCollab.Data;
    using HotelCollab.Data.Models;
    using HotelCollab.Services;
    using HotelCollab.Services.Interfaces;
    using HotelCollab.ViewModels.Hotels;
    using Microsoft.AspNetCore.Mvc;
    using System.Diagnostics;
    using System.Threading.Tasks;

    public class HotelController : Controller
    {
        private readonly IHotelService hotelService;

        public HotelController(IHotelService hotelService)
        {
            this.hotelService = hotelService;
        }

        public IActionResult Register()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterHotel(HotelRegisterViewModel model)
        {
            model.Image = Request.Form.Files["image"];

            await hotelService.AddHotelAsync(model);

            return this.Redirect("/Home/Index");
        }
    }
}

src/HotelCollab/Controllers/UserController.cs
using HotelCollab.Services.Interfaces;
using HotelCollab.ViewModels.Hotels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCollab.Controllers
{
    public class UserController : Controller
    {
        private readonly IRequestService requestService;

        public UserController(IRequestService requestService)
        {
            this.requestService = requestService;
        }

        [HttpPost]
        public async Task<IActionResult> CreateRequest(GetHotelsViewModel model)
        {
            await requestService.CreateRequestAsync(model);

            return this.Redirect("/Home/Index");
        }
    }
}

src/HotelCollab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Хотел Мениджър</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/images/logos/hotel_manager3_3.png" rel="icon">
    <link href="~/images/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendors/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendors/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/vendors/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendors/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendors/venobox/venobox.css" rel="stylesheet">
    <link href="~/vendors/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/vendors/aos/aos.css" rel="stylesheet">

    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo mr-auto"><a href="index.html">Хотел Мениджър</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo mr-auto"><img src="assets/images/logo.png" alt="" class="img-fluid"></a>-->

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active">
                        <a asp-controller="Home" asp-action="Index">Начало</a>
                    </li>
                    <li>
                        <a href="#about">За нас</a>
                    </li>
                    <li>
                        <a href="#services">Услуги</a>
                    </li>
                </ul>
            </nav><!-- .nav-menu -->

            <a asp-area="Identity" asp-controller="Account" asp-action="Login" class="get-started-btn scrollto">Започни сега</a>
        </div>
    </header><!-- End Header -->

    @this.RenderBody()

    <footer id="footer">
        <div class="container footer-bottom clearfix">
            <div class="copyright">
                Проект №147 - <strong><span>Хотел Мениджър</span></strong>
            </div>
            <div class="credits">
                НОИТ 2020/2021
            </div>
        </div>
    </footer><!-- End Footer -->
    <!-- Vendor JS Files -->
    <script src="~/vendors/jquery/jquery.min.js"></script>
    <script src="~/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendors/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/vendors/php-email-form/validate.js"></script>
    <script src="~/vendors/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/vendors/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/vendors/venobox/venobox.min.js"></script>
    <script src="~/vendors/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/vendors/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/index.js"></script>

    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/HotelCollab/Views/Shared/_LogOutLayout.cshtml
<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Хотел Мениджър</title>

    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href="~/css/app.css" rel="stylesheet">
    <link rel="stylesheet" href="~/vendors/chartjs/Chart.min.css">
    <link rel="stylesheet" href="~/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/css/app.css">
    <link rel="shortcut icon" href="~/images/logos/hotel_manager3_3.png" type="image/x-icon">
</head>
<body>

    @this.RenderBody()


    <script src="~/js/feather-icons/feather.min.js"></script>
    <script src="~/js/app.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/vendors/chartjs/Chart.min.js"></script>
    <script src="~/vendors/apexcharts/apexcharts.min.js"></script>
    <script src="~/js/pages/dashboard.js"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/HotelCollab/Views/Shared/_LoggedLayout.cshtml
@using HotelCollab.ViewModels.Hotels
@model GetHotelsViewModel

<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Хотел Мениджър</title>

    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href="~/css/app.css" rel="stylesheet">
    <link rel="stylesheet" href="~/vendors/chartjs/Chart.min.css">
    <link rel="stylesheet" href="~/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/css/app.css">
    <link rel="shortcut icon" href="~/images/logos/hotel_manager3_3.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
</head>
<body>
    <div id="app">
        <div id="sidebar" class='active'>
            <div class="sidebar-wrapper active">
                <div class="sidebar-header">
                    <img src="~/images/hotel_manager3_4.png" alt="" srcset="">
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class='sidebar-title'>Моят профил</li>

                        <li class="sidebar-item">
                            <a href="#" class='sidebar-link'>
                                <i data-feather="settings" width="20"></i>
                                <span>Настройки</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            </div>
        </div>

        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        @if (bool.Parse(this.User.FindFirst("IsManager").Value))
                        {
                            <li class="dropdown nav-icon mr-3">

                                <a asp-controller="Hotel" asp-action="Register">
                                    <div class="d-lg-inline-block">
                                        <i class="fas fa-plus"></i>
                                    </div>
                                </a>

                            </li>
                        }
                        <li class="dropdown nav-icon mr-3">
                            <a href="#" data-toggle="modal" data-target="#border-less">
                                <div class="d-lg-inline-block">
                                    <i class="fas fa-sign-in-alt"></i>
                                </div>
                            </a>
                            <div class="modal fade text-left modal-borderless" id="border-less" tabindex="-1"
                                 role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-scrollable" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Присъедини се към хотел</h5>
                                            <button type="button" class="close rounded-pill" data-dismiss="modal"
                                                    aria-label="Close">
                                                <i data-feather="x"></i>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="col-md-12 mb-6">
                                                <form asp-controller="User" asp-action="CreateRequest" method="post">
                                                    <label>Изберете хотел</label>
                                                    <select asp-for="HotelId" class="choices form-select">
                                                        @foreach (var item in Model.Hotels)
                                                        {
                                                            <option value="@item.Id">@item.Name, @item.Town.Name</option>
                                                        }
                                                    </select>

                                                    <label>Изберете роля</label>
                                                    <select asp-for="Role" class="choices form-select">
                                                        <option value="Receptionist">Receptionist</option>
                                                        <option value="Cleaner">Cleaner</option>
                                                    </select>

                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-light-primary"
                                                                data-dismiss="modal">
                                                            <i class="bx bx-x d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Затвори</span>
                                                        </button>
                                                        <button type="submit" class="btn btn-primary ml-1"
                                                                data-dismiss="modal">
                                                            <i class="bx bx-check d-block d-sm-none"></i>
                                                            <span class="d-none d-sm-block">Подтвърди</span>
                                                        </button>
                                                    </div>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown"
                               class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="~/images/avatar/avatar-s-1.png" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Здравей, @(this.User.FindFirst("FirstName").Value) !</div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> Профил</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Identity" asp-controller="Account" asp-action="Logout"><i data-feather="log-out"></i> Изход</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            @this.RenderBody()

        </div>
    </div>
    <script src="~/js/feather-icons/feather.min.js"></script>
    <script src="~/js/app.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/vendors/chartjs/Chart.min.js"></script>
    <script src="~/vendors/apexcharts/apexcharts.min.js"></script>
    <script src="~/js/pages/dashboard.js"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>