src/HotelCollab/Areas/Manager/ViewModels/RequestsViewModel.cs
using HotelCollab.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCollab.Areas.Manager.ViewModels
{
    public class RequestsViewModel
    {
        public List<Request> Requests { get; set; }
    }
}

src/HotelCollab/ViewModels/User/UserDashboardViewModel.cs
namespace HotelCollab.ViewModels.User
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using HotelCollab.Data.Models;

    public class UserDashboardViewModel
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }
    }
}

src/HotelCollab/Areas/Manager/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCollab.Areas.Manager.Controllers
{
    public class EmployeeController : Controller
    {
        [Authorize]
        [Area("Manager")]
        public IActionResult Overview()
        {
            return View();
        }
    }
}

src/HotelCollab/Areas/Manager/Controllers/RequestsController.cs
using HotelCollab.Data;
using HotelCollab.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCollab.Areas.Manager.Controllers
{
    public class RequestsController : Controller
    {
        private readonly IRepository<UserHotels> userHotelsRepo;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IRepository<Request> requestRepo;
        private readonly IRepository<ApplicationUser> userRepo;
        private readonly IRepository<ApplicationRole> roleRepo;

        public RequestsController(IRepository<UserHotels> userHotelsRepo, UserManager<ApplicationUser> userManager, IRepository<Request> requestRepo, IRepository<ApplicationUser> userRepo, IRepository<ApplicationRole> roleRepo)
        {
            this.userHotelsRepo = userHotelsRepo;
            this.userManager = userManager;
            this.requestRepo = requestRepo;
            this.userRepo = userRepo;
            this.roleRepo = roleRepo;
        }

        [Authorize]
        [Area("Manager")]
        [HttpPost]
        public async Task<IActionResult> Finish(string id)
        { 
            var request = (await requestRepo.GetAllAsync()).FirstOrDefault(r => r.Id == id);

            var role = (await roleRepo.GetAllAsync()).FirstOrDefault(r => r.Name == request.Role);

            var user = await userRepo.GetAsync(request.UserId);

            var userHotels = new UserHotels()
            {
                UserId = request.UserId,
                HotelId = request.HotelId,
                RoleId = role.Id,
            };

            await this.userManager.AddToRoleAsync(user, role.Name);
            await userHotelsRepo.AddAsync(userHotels);
            await userHotelsRepo.SaveChangesAsync();

            requestRepo.Delete(request);
            await requestRepo.SaveChangesAsync();

            return Redirect("/Manager/Users/Requests");
        }
    }
}

src/HotelCollab/Areas/Manager/Controllers/UsersController.cs
using HotelCollab.Areas.Manager.ViewModels;
using HotelCollab.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCollab.Areas.Manager.Controllers
{
    public class UsersController : Controller
    {
        private readonly IRequestService requestService;

        public UsersController(IRequestService requestService)
        {
            this.requestService = requestService;
        }

        [Authorize]
        [Area("Manager")]
        public IActionResult Employees()
        {
            return View();
        }

        [Authorize]
        [Area("Manager")]
        public async Task<IActionResult> Requests()
        {
            var result = new RequestsViewModel()
            {
                Requests =( await requestService.GetAllRequestsAsync()),
            };

            return this.View(result);
        }
    }
}

src/HotelCollab/Controllers/UserController.cs
using HotelCollab.Services.Interfaces;
using HotelCollab.ViewModels.Hotels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelCollab.Controllers
{
    public class UserController : Controller
    {
        private readonly IRequestService requestService;

        public UserController(IRequestService requestService)
        {
            this.requestService = requestService;
        }

        [HttpPost]
        public async Task<IActionResult> CreateRequest(GetHotelsViewModel model)
        {
            await requestService.CreateRequestAsync(model);

            return this.Redirect("/Home/Index");
        }
    }
}

src/HotelCollab/Areas/Manager/Views/Users/Employees.cshtml
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-12">
                <h3>Служители</h3>
                <p class="text-subtitle">
                    Тук може да следите прогреса на вашите служители и да управлявате
                    профилите им.
                </p>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                Служители
            </div>
            <div class="card-body">
                <div class="col-md-12">

                    <table class='table table-striped' id="table1">
                        <thead>
                            <tr>
                                <th>Профил</th>
                                <th>Име</th>
                                <th>Служител</th>
                                <th>Детайли</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <div class="avatar bg-warning ">
                                        <img src="~/images/avatar/avatar-s-4.png" alt="" srcset="">
                                    </div>
                                </td>
                                <td>Иван Петров</td>
                                <td>Рецепционист</td>
                                <td><a href="initial-employee.html">Отвори</a></td>

                            </tr>

                            <tr>
                                <td>
                                    <div class="avatar bg-warning ">
                                        <img src="assets/images/avatar/avatar-s-4.png" alt="" srcset="">
                                    </div>
                                </td>
                                <td>Иван Петров</td>
                                <td>Рецепционист</td>
                                <td><a href="initial-employee.html">Отвори</a></td>

                            </tr>

                            <tr>
                                <td>
                                    <div class="avatar bg-warning ">
                                        <img src="assets/images/avatar/avatar-s-4.png" alt="" srcset="">
                                    </div>
                                </td>
                                <td>Иван Петров</td>
                                <td>Рецепционист</td>
                                <td><a href="initial-employee.html">Отвори</a></td>


                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </section>

</div>

src/HotelCollab/Areas/Manager/Views/Users/Requests.cshtml
@model HotelCollab.Areas.Manager.ViewModels.RequestsViewModel

<div class="main-content container-fluid">
    <div class="page-title">
        <h3>Заявки</h3>
        <p class="text-subtitle text-muted">Тук може подтвърдите заявките за регистрация, подадени от служителите.</p>
    </div>
    <div class="card widget-todo">
        <div class="card-header border-bottom d-flex justify-content-between align-items-center">
            <h4 class="card-title d-flex">
                <i class='bx bx-check font-medium-5 pl-25 pr-75'></i>Подадени заявки
            </h4>

        </div>
        <div class="card-body px-0 py-1">
            <ul class="widget-todo-list-wrapper" id="widget-todo-list">
                @foreach (var request in Model.Requests)
                {
                    <li class="widget-todo-item">
                        <div class="widget-todo-title-wrapper d-flex justify-content-between align-items-center mb-50">
                            <div class="widget-todo-title-area d-flex align-items-center">
                                <div class="checkbox checkbox-shadow">
                                    <input type="checkbox" class="form-check-input" id="checkbox1" data-toggle="modal" data-target="#default">
                                    <label for="checkbox1"></label>
                                </div>
                                <span class="widget-todo-title ml-50"> @request.User.FirstName @request.User.LastName - @request.Role, подадена на @request.CreatedOn.Date.ToShortDateString() г.</span>
                                <div class="modal fade text-left" id="default" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
                                     aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="myModalLabel1">@request.User.FirstName @request.User.LastName - @request.Role, подадена на @request.CreatedOn.Date.ToShortDateString() г.</h5>
                                                <button type="button" class="close rounded-pill" data-dismiss="modal" aria-label="Close">
                                                    <i data-feather="x"></i>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                    Сигурни ли сте, че искате да подтвърдите заявката?
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn" data-dismiss="modal">
                                                    <i class="bx bx-x d-block d-sm-none"></i>
                                                    <span class="d-none d-sm-block">Затвори</span>
                                                </button>
                                                <form asp-area="Manager" asp-controller="Requests" asp-action="Finish" asp-route-id="@request.Id" method="post">
                                                    <input type="submit" class="btn btn-primary ml-1" name="name" value="Потвърди"/>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>